version: "3"

services:
  webapp:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8081:8080
  python-docker:
    build:
      dockerfile: Dockerfile-dind-drrobt
      context: ./
